### ISSUE TITLE
xsd:import and xsd:include support

### ISSUE THREAD

**Issue by iurisilvio** [FlightDataServices/Soapbox#19]
I have a WSDL with `xsd:import` in my schema definition.

How can I handle it? Is it possible to extend soapbox to support it?

**Comment by iurisilvio** [comment]
I'm trying to make it work. I will try to provide a patch with my changed after that.

I discovered `xsd:import` is supported, but it does not work with my WSDL. It has a schema import with the same namespace. It is not expected by soapbox.

```xml
<?xml version="1.0" encoding="UTF-8"?>
    <wsdl:definitions
            name="Name"
            targetNamespace="http://mynamespace.com/X"
            xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
            xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
            <xsd:schema>
                <xsd:import namespace="http://mynamespace.com/X" schemaLocation="file1.xsd"/>
                <xsd:import namespace="http://mynamespace.com/X" schemaLocation="file2.xsd"/>
            </xsd:schema>
...
```

I'm not sure if it is a valid format, I probably can replace it with `xsd:include`, but soapbox does not load `xsd:include`s.

**Comment by FelixSchwarz** [comment]
I implemented (most of) WSDL imports in my soapbox fork ( https://github.com/FelixSchwarz/soapfish )

**Comment by iurisilvio** [comment]
@FelixSchwarz  Thanks! I will check that!

**Comment by pope1ni** [comment]
Closing as this has been implemented in soapfish.
