### ISSUE TITLE
Soapbox script xsd2py fails on 'from lxml import etree' because of TypeError: encode argument must be string without null bytes, not unicode

### ISSUE THREAD

**Issue by AncientSwordRage** [FlightDataServices/Soapbox#20]
I'm on Python2.7, on Centos 6.3,  using Soapbox 0.3.7.

I'm trying to run the xsd2py script over my .xsd file that has references to utf-8. I'm unsure whether Soapbox can handle that encoding, or if it perhaps needs special options passed in.

I also don't know if it's more my local setup than anything else (though I've done nothing special).

I've also asked this on [Stackoverflow](http://stackoverflow.com/q/30056737/1075247), and no one has an answer yet, so I'm assuming it's a fault with soapbox.

**Comment by kirku1g** [comment]
From what I can find online regarding the issue, this error can occur if the version of Python which lxml was built against differs from the version of the Python you're using to run xsd2py. Are you using a virtualenv or the system level Python?

This [stackoverflow] (http://stackoverflow.com/questions/9465248/runtimewarning-compiletime-version-2-6-of-module-lxml-etree-does-not-match-ru) answer describes reinstalling easy_install, pip and lxml to ensure it's compatible.

**Comment by AncientSwordRage** [comment]
@kirku1g  I'm about to go check the version of lxml and where it lives on my machine. The machine doesn't have access to the internet so it's not as easy as just using pip etc. I'll update this issue if I solve it though.

**Comment by AncientSwordRage** [comment]
@kirku1g  Yeah it's pointed at python2.6 I'll work out how to get the right version of lxml
