### ISSUE TITLE
Incorrect Source Code Links on PyPi

### ISSUE THREAD

**Issue by GadgetSteve** [FlightDataServices/Soapbox#21]
The entry on PyPi for version 0.3.7 incorrectly states source code available at http://code.google.com/p/soapbox/ as does the documentation at https://pythonhosted.org/Soapbox/Introduction.html#source-code

**Comment by pope1ni** [comment]
Thanks. Please be aware that we cannot currently dedicate time to maintaining Soapbox. We recommend that you use the [soapfish](https://github.com/FelixSchwarz/soapfish/) fork.
